const ACCESS_LOG=[];
const CHECKIN_QUEUE=[];
const DOCS_QUEUE=[];
const CHAT_CHANNELS=[];
const CHAT_MESSAGES={};
const DM_THREADS=[];
const CHAT_REPORTS=[];
const VENDING_SALES=[];
const PROMO_CODES=[];
const GYM_INFO={name:'Iron Syndacate Gym',tagline:'Forza. Disciplina. Costanza.',address:"Via dell'Industria 12, Valeggio sul Mincio (VR)",phone:'+39 045 000 0000',email:'info@ironsyndacate.gym',whatsapp:'+39 333 000 0000',instagram:'@ironsyndacate.gym',hours:[{d:'Lun – Ven',h:'06:00 – 23:00'},{d:'Sabato',h:'08:00 – 20:00'},{d:'Domenica',h:'09:00 – 13:00'},{d:'Festivi',h:'Chiuso'}]};
Object.assign(window,{ACCESS_LOG,CHECKIN_QUEUE,DOCS_QUEUE,CHAT_CHANNELS,CHAT_MESSAGES,DM_THREADS,CHAT_REPORTS,VENDING_SALES,PROMO_CODES,GYM_INFO});