const QUOTES=["La disciplina pesa meno del rimpianto.","Non devi essere motivato ogni giorno. Devi essere costante.","Il ferro non mente: restituisce esattamente ciò che gli dai.","Ogni ripetizione è un voto per la persona che vuoi diventare.","La forza si costruisce quando nessuno guarda.","Oggi non si salta. Oggi si costruisce.","Non sei qui per allenarti. Sei qui per costruirti.","Il ferro seleziona. La costanza costruisce."];
function quoteOfTheDay(){const now=new Date();const start=new Date(now.getFullYear(),0,0);const day=Math.floor((now-start)/86400000);return QUOTES[day%QUOTES.length];}
const SERVICES=[{id:'bb',tag:'01',it:'Bodybuilding',en:'Hypertrophy',desc:'Ipertrofia e composizione corporea.'},{id:'str',tag:'02',it:'Allenamento Forza',en:'Strength',desc:'Powerlifting, alzate fondamentali.'},{id:'plate',tag:'03',it:'Plate Loaded Area',en:'Plate Loaded',desc:'Linea completa Panatta a dischi.'},{id:'pt',tag:'04',it:'Personal Training',en:'1:1 Coaching',desc:'Coaching individuale con trainer certificati.'},{id:'duo',tag:'05',it:'Allenamento Coppia',en:'Duo Training',desc:'Allenati con un partner.'},{id:'sgt',tag:'06',it:'Small Group',en:'Small Group',desc:'Gruppi ridotti.'},{id:'fun',tag:'07',it:'Hybrid / Functional',en:'Functional',desc:'Condizionamento ibrido.'},{id:'evt',tag:'08',it:'Eventi & Challenge',en:'Events',desc:'Test day, gare interne.'}];
const PLANS=[{id:'start',name:'Iron Start',period:'Mensile',en:'Monthly',price:49,unit:'/mese',tagline:'Inizia il percorso.',features:['Accesso illimitato sala pesi','Linea Panatta completa','App e tessera QR','Citazione del giorno'],highlight:false},{id:'progress',name:'Iron Progress',period:'Trimestrale',en:'Quarterly',price:129,unit:'/3 mesi',tagline:'Costruisci slancio.',save:'Risparmi 18€',features:['Tutto di Iron Start','1 check tecnico incluso','Sospensione 7 giorni','Accesso eventi base'],highlight:false},{id:'discipline',name:'Iron Discipline',period:'Semestrale',en:'6 months',price:229,unit:'/6 mesi',tagline:'La scelta della costanza.',save:'Risparmi 65€',features:['Tutto di Iron Progress','1 scheda personalizzata','2 ingressi ospite','Sconto 10% distributori'],highlight:true,badge:'Più scelto'},{id:'legacy',name:'Iron Legacy',period:'Annuale',en:'Annual',price:399,unit:'/anno',tagline:'Per chi non si ferma.',save:'Risparmi 189€',features:['Tutto di Iron Discipline','3 sessioni PT incluse','Accesso prioritario eventi','Sospensione 30 giorni'],highlight:false}];
const PT_PACKS=[{id:'pt1',name:'PT Single Session',price:45,unit:'sessione',desc:'Lezione individuale 60 min.'},{id:'duo',name:'PT Duo',price:30,unit:'a testa',desc:'Sessione di coppia, 60 min.'},{id:'sgt',name:'Small Group',price:18,unit:'a testa',desc:'Fino a 5 persone, 60 min.'}];
const EVENTS=[];
const VENDING=[];
const STATUS={active:{it:'Attivo',tone:'ok'},expiring:{it:'In scadenza',tone:'warn'},suspended:{it:'Sospeso',tone:'mute'},cert_missing:{it:'Certificato mancante',tone:'bad'},cert_expired:{it:'Certificato scaduto',tone:'bad'},doc_review:{it:'Documento da validare',tone:'info'},unpaid:{it:'Pagamento insoluto',tone:'bad'}};
const CLIENTS=[];
const KPI={activeMembers:0,newSignups:0,expiringSubs:0,certMissing:0,docsToReview:0,todayBookings:0,revenueToday:0,revenueMonth:0,accessToday:0,vendingMonth:0};
const REVENUE_SERIES=[];
const ACCESS_SERIES=[];
const TODAY_BOOKINGS=[];
const TODO_ITEMS=[];
const RECENT_ACCESS=[];
Object.assign(window,{QUOTES,quoteOfTheDay,SERVICES,PLANS,PT_PACKS,EVENTS,VENDING,STATUS,CLIENTS,KPI,REVENUE_SERIES,ACCESS_SERIES,TODAY_BOOKINGS,TODO_ITEMS,RECENT_ACCESS});