const ME=null;
const TRAINERS=[{id:'mf',name:'Matteo Ferraro',short:'M. Ferraro',role:'Head Coach · Forza',specialty:'Powerlifting, forza massimale, alzate fondamentali',rating:4.9},{id:'sv',name:'Sara Vinco',short:'S. Vinco',role:'Coach · Mobility & Functional',specialty:'Mobilità, ibrido, prevenzione infortuni',rating:4.8},{id:'lb',name:'Luca Bertoldi',short:'L. Bertoldi',role:'Coach · Bodybuilding',specialty:'Ipertrofia, ricomposizione, gara',rating:4.9}];
const BOOKING_TYPES=[{id:'single',name:'PT Singolo',desc:'1:1 con il coach · 60 min',price:45,icon:'user'},{id:'duo',name:'PT Coppia',desc:'Con un partner · 60 min',price:30,icon:'users'},{id:'group',name:'Small Group',desc:'Fino a 5 persone · 60 min',price:18,icon:'users'},{id:'check',name:'Check tecnico',desc:'Valutazione e scheda · 45 min',price:0,icon:'doc'}];
const BOOK_DAYS=[{d:'Lun',n:'02',full:false},{d:'Mar',n:'03',full:false},{d:'Mer',n:'04',full:false},{d:'Gio',n:'05',full:false},{d:'Ven',n:'06',full:false},{d:'Sab',n:'07',full:true}];
const BOOK_SLOTS=[{t:'07:00',free:true},{t:'08:30',free:true},{t:'10:00',free:false},{t:'12:00',free:true},{t:'17:30',free:false},{t:'19:00',free:true},{t:'20:30',free:true}];
const MY_BOOKINGS=[];
const MY_DOCS=[];
const docClientMap={valid:{tone:'ok',label:'Valido'},review:{tone:'info',label:'In revisione'},expired:{tone:'bad',label:'Scaduto'},missing:{tone:'warn',label:'Mancante'}};
const NOTIFS=[];
const CLIENT_DM=[];
Object.assign(window,{ME,TRAINERS,BOOKING_TYPES,BOOK_DAYS,BOOK_SLOTS,MY_BOOKINGS,MY_DOCS,docClientMap,NOTIFS,CLIENT_DM});